version: '3.7'

services:
  grafana:
    build: 'images/grafana-image'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    build: 'images/prometheus-image'
    ports:
      - 9001:9090
    volumes:
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
    depends_on:
      grafana:
        condition: service_started
networks:
  monitoring: